settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: go-cve-dictionary
  path: /Users/kota/go/src/github.com/kotakanbe/go-cve-dictionary
  commands:
    vet:
      status: true
    test:
      status: true
    install:
      status: false
    build:
      status: true
    run:
      status: false
  watcher:
    paths:
    - /
    extensions:
    - go
    ignored_paths:
    - .git
    - .realize
    - vendor
