
[[constraint]]
  name = "github.com/sirupsen/logrus"
  branch = "master"

[[constraint]]
  name = "github.com/kotakanbe/logrus-prefixed-formatter"
  branch = "master"

[[constraint]]
  name = "github.com/cheggaaa/pb"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"
